---
title: "Check for held-out test set balance"
author: "Canaan"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidylog)
library(readxl)
setwd("G:/My Drive/MIT/Research/lm-informants/data/MakingOverTrainSet/")
```


combine all into file 

```{r}

file_pattern <- "sampleSalad*"  # Change this pattern as needed

file_list <- list.files(path = ".", pattern = file_pattern, full.names = TRUE)

combined_data <- file_list %>%
  map_df(~ read_csv(.x, col_names = F)) %>% 
  distinct()


```


write out to get scored

```{r}
combined_data %>% 
  write_csv("WordsToBeScored_11.5.2023.txt", col_names = F)
```

```{r}




dat <- read.delim("blickTestResults.txt") %>%
  select(word,score) %>% 
  filter(score != "score") %>% 
  mutate(length = str_count(word," ")) %>% 
  mutate(score_binarized = if_else(score > 2.53, F, T)) %>% 
  filter(length > 1)

t <- dat %>% 
  group_by(score_binarized,length) %>% 
  summarise(n=n())

min_in_cat <- t %>% 
  group_by(length) %>% 
  summarise(min = min(n))

l <- c()
for (i in 1:nrow(min_in_cat)){
  current_row <- min_in_cat[i,]
  num_rows_to_sample <- current_row$min
  current_length <- current_row$length
  print(current_length)
  print(num_rows_to_sample)
  all_at_this_length <- dat %>% 
  filter(length == current_length)

bads <- all_at_this_length %>% 
  filter(score_binarized == FALSE) %>% 
  sample_n(num_rows_to_sample, replace = F)

goods <- all_at_this_length %>% 
  filter(score_binarized == T) %>% 
  sample_n(num_rows_to_sample, replace = F)

l <- rbind(l,goods,bads)
  
}
group_five_subsampled <- bind_rows(l) %>% 
  select(word,score_binarized)


write_csv(group_five_subsampled,"EnglishOverTrainingData.csv")

```

